//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderBrowserDialog.Images {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Icons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FolderBrowserDialog.Images.Icons", typeof(Icons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Images\img_folder_explorer_32pxl.png.
        /// </summary>
        public static string ButtonFind {
            get {
                return ResourceManager.GetString("ButtonFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Images\img_hard_drive_32pxl.png.
        /// </summary>
        public static string TreeViewItemDrive {
            get {
                return ResourceManager.GetString("TreeViewItemDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Images\img_yellow_folder_closed_32pxl.png.
        /// </summary>
        public static string TreeViewItemFolderClosed {
            get {
                return ResourceManager.GetString("TreeViewItemFolderClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Images\img_folder_noaccess_32pxl.png.
        /// </summary>
        public static string TreeViewItemFolderNoAccess {
            get {
                return ResourceManager.GetString("TreeViewItemFolderNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Images\img_yellow_folder_open_32pxl.png.
        /// </summary>
        public static string TreeViewItemFolderOpen {
            get {
                return ResourceManager.GetString("TreeViewItemFolderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Images\img_my_computer_32pxl.png.
        /// </summary>
        public static string TreeViewItemMyComputer {
            get {
                return ResourceManager.GetString("TreeViewItemMyComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Images\img_hard_drive_network_32pxl.png.
        /// </summary>
        public static string TreeViewItemNetworkDrive {
            get {
                return ResourceManager.GetString("TreeViewItemNetworkDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Images\img_hard_drive_system_32pxl.png.
        /// </summary>
        public static string TreeViewItemSystemDrive {
            get {
                return ResourceManager.GetString("TreeViewItemSystemDrive", resourceCulture);
            }
        }
    }
}
